"use client";

import { Activity, ArrowRight, BadgeCheck, Bell, CalendarDays, Check, ChevronDown, CircleHelp, FolderHeart, Gauge, ImagePlus, LockKeyhole, Menu, MoreHorizontal, Plus, QrCode, Search, Settings, ShieldCheck, Sparkles, TicketCheck, UserPlus, Users, X, Zap } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import QRCode from "qrcode";
import Image from "next/image";

type View = "overview" | "campaigns" | "collections" | "verification" | "profile" | "moderation";
type CreatorProfile = { username: string; firstName: string; lastName: string; bio: string; isSuperAdmin: boolean };
type Campaign = { id: string; name: string; description: string; eventType: string; venue: string; startsAt: string | null; endsAt: string | null; total: number; claimed: number; status: string; reviewStatus: string; imageUrl: string; qrEnabled: boolean; qrToken: string | null; secretEnabled: boolean; editable: boolean; rejectionReason: string; collaborators: string[]; createdAt: string };

const baseNav: { id: View; label: string; icon: typeof Gauge }[] = [
  { id: "overview", label: "Inicio", icon: Gauge }, { id: "campaigns", label: "Coleccionables", icon: Zap },
  { id: "collections", label: "Colecciones", icon: FolderHeart }, { id: "verification", label: "Verificación", icon: ShieldCheck },
  { id: "profile", label: "Mi perfil", icon: Users },
];
const formatNumber = (value: number) => new Intl.NumberFormat("es-CL").format(value);
const formatDate = (value: string | null) => value ? new Date(value).toLocaleDateString("es-CL", { day: "2-digit", month: "short", year: "numeric" }).toUpperCase() : "SIN FECHA";
const statusClass = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s/g, "-");

function PillArtwork({ campaign, large = false }: { campaign: Campaign; large?: boolean }) {
  const initials = campaign.name.split(" ").map((word) => word[0]).join("").slice(0, 3).toUpperCase();
  return <div className={`pill-art ${large ? "pill-art-large" : ""} ${campaign.imageUrl ? "pill-art-uploaded" : ""}`} style={{ "--pill": "#1f6f78", "--pill-soft": "#c6eff1" } as React.CSSProperties}>
    {campaign.imageUrl && <span className="pill-uploaded-art" style={{ backgroundImage: `url(${campaign.imageUrl})` }} />}
    <div className="pill-cut pill-cut-top" /><div className="pill-cut pill-cut-bottom" /><span className="pill-year">PILLS® / {campaign.startsAt?.slice(0, 4) ?? "—"}</span>
    <div className="pill-core"><Sparkles size={large ? 25 : 18} /><strong>{initials}</strong></div><span className="pill-caption">{campaign.eventType}</span>
  </div>;
}

export default function CreatorStudio() {
  const router = useRouter();
  const [view, setView] = useState<View>("overview"); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [profile, setProfile] = useState<CreatorProfile | null>(null);
  const [showCreate, setShowCreate] = useState(false); const [managing, setManaging] = useState<Campaign | null>(null); const [showMenu, setShowMenu] = useState(false);
  const [search, setSearch] = useState(""); const [toast, setToast] = useState(""); const [loading, setLoading] = useState(true);
  const navItems = useMemo(() => profile?.isSuperAdmin ? [...baseNav, { id: "moderation" as View, label: "Curaduría", icon: BadgeCheck }] : baseNav, [profile]);
  const filtered = useMemo(() => campaigns.filter((campaign) => `${campaign.name} ${campaign.eventType} ${campaign.venue}`.toLowerCase().includes(search.toLowerCase())), [campaigns, search]);

  async function loadCampaigns() { const response = await fetch("/api/collectibles", { cache: "no-store" }); const result = await response.json(); if (response.ok) setCampaigns(result.collectibles); else setToast(result.error || "No pudimos cargar tus coleccionables"); }
  useEffect(() => { Promise.all([fetch("/api/profile/me", { cache: "no-store" }), fetch("/api/collectibles", { cache: "no-store" })]).then(async ([profileResponse, campaignsResponse]) => {
    if (profileResponse.status === 401) { router.replace("/login"); return; } const profileData = await profileResponse.json(); if (!profileData.username) { router.replace("/onboarding"); return; }
    setProfile(profileData); const campaignData = await campaignsResponse.json(); if (campaignsResponse.ok) setCampaigns(campaignData.collectibles); else setToast(campaignData.error || "No pudimos cargar tus coleccionables"); setLoading(false);
  }).catch(() => { setToast("No pudimos cargar tu espacio"); setLoading(false); }); }, [router]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3200); return () => window.clearTimeout(timer); }, [toast]);
  async function createCampaign(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/collectibles", { method: "POST", body: new FormData(event.currentTarget) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "No pudimos guardar el coleccionable."); setCampaigns((current) => [result.collectible, ...current]); setShowCreate(false); setView("campaigns"); setToast("Solicitud guardada y enviada a curaduría"); }
  const title = navItems.find((item) => item.id === view)?.label ?? "Inicio";
  if (loading) return <main className="studio-loading"><span className="brand-mark"><span /></span><strong>Cargando Pills…</strong></main>;

  return <main className="app-shell"><aside className={`sidebar ${showMenu ? "sidebar-open" : ""}`}><div className="brand"><span className="brand-mark"><span /></span><strong>Pills</strong><em>Creator Studio</em></div>
    <button className="workspace-switch" onClick={() => setView("profile")}><span className="avatar avatar-orange">{profile?.username.slice(0, 2).toUpperCase()}</span><span><strong>@{profile?.username}</strong><small>Cuenta personal</small></span><ChevronDown size={15} /></button>
    <nav><p className="nav-label">Workspace</p>{navItems.map((item) => <button key={item.id} className={view === item.id ? "nav-active" : ""} onClick={() => { setView(item.id); setShowMenu(false); }}><item.icon size={18} />{item.label}{item.id === "moderation" && <span className="nav-dot" />}</button>)}</nav>
    <div className="sidebar-bottom"><button><CircleHelp size={18} />Centro de ayuda</button><button onClick={() => setView("profile")}><Settings size={18} />Configuración</button><div className="plan-card"><span>PLAN INICIAL</span><strong>{campaigns.length} coleccionables</strong><small>Tu espacio de creación</small><div><i style={{ width: "0%" }} /></div></div><button className="user-row" onClick={async () => { await fetch("/auth/signout", { method: "POST" }); router.replace("/login"); router.refresh(); }}><span className="avatar">{profile?.username.slice(0, 2).toUpperCase()}</span><span><strong>{profile?.firstName || `@${profile?.username}`}</strong><small>Cerrar sesión</small></span><MoreHorizontal size={17} /></button></div></aside>
    <section className="main-panel"><header className="topbar"><button className="mobile-menu" onClick={() => setShowMenu((value) => !value)}>{showMenu ? <X /> : <Menu />}</button><div><span className="eyebrow">Creator Studio</span><h1>{title}</h1></div><div className="top-actions"><label className="global-search"><Search size={17} /><input aria-label="Buscar coleccionables" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar" /></label><button className="icon-button" aria-label="Notificaciones"><Bell size={19} /></button><button className="primary-button" onClick={() => setShowCreate(true)}><Plus size={18} />Nuevo coleccionable</button></div></header>
      <div className="content">{view === "overview" && <Overview campaigns={campaigns} onCreate={() => setShowCreate(true)} onNavigate={setView} onManage={setManaging} />}{view === "campaigns" && <Campaigns campaigns={filtered} onCreate={() => setShowCreate(true)} onManage={setManaging} />}{view === "collections" && <Collections campaigns={campaigns} />}{view === "verification" && <Verification />}{view === "profile" && profile && <Profile profile={profile} onSaved={setProfile} />}{view === "moderation" && profile?.isSuperAdmin && <Moderation onChanged={() => { void loadCampaigns(); setToast("Decisión de curaduría guardada"); }} />}</div></section>
    {showCreate && <CreateCampaign onClose={() => setShowCreate(false)} onSubmit={createCampaign} />}{managing && <ManageCampaign campaign={managing} onClose={() => setManaging(null)} onSaved={(updated) => { setCampaigns((items) => items.map((item) => item.id === updated.id ? { ...item, ...updated } : item)); setManaging(updated); setToast("Coleccionable actualizado"); }} />}{toast && <div className="toast"><span><Check size={16} /></span>{toast}</div>}{showMenu && <button className="scrim" aria-label="Cerrar menú" onClick={() => setShowMenu(false)} />}</main>;
}

function Overview({ campaigns, onCreate, onNavigate, onManage }: { campaigns: Campaign[]; onCreate: () => void; onNavigate: (view: View) => void; onManage: (campaign: Campaign) => void }) {
  const claimed = campaigns.reduce((sum, item) => sum + item.claimed, 0);
  return <><section className="welcome"><div><span className="section-kicker"><span /> TU ESPACIO DE CREACIÓN</span><h2>Convierte cada evento<br />en una colección.</h2><p>Diseña recuerdos digitales que tus fans van a querer guardar.</p></div><button className="primary-button primary-large" onClick={onCreate}>Crear coleccionable <ArrowRight size={19} /></button></section><section className="metrics-grid"><article><div className="metric-icon"><TicketCheck /></div><span>Pills coleccionadas</span><strong>{formatNumber(claimed)}</strong><small><em>En todos tus coleccionables</em></small></article><article><div className="metric-icon purple"><Users /></div><span>Solicitudes en revisión</span><strong>{campaigns.filter((item) => item.reviewStatus === "pending").length}</strong><small><em>Curaduría de Pills</em></small></article><article><div className="metric-icon green"><Activity /></div><span>Aprobados</span><strong>{campaigns.filter((item) => item.reviewStatus === "approved").length}</strong><small><em>Listos para distribuir</em></small></article><article><div className="metric-icon gold"><FolderHeart /></div><span>Total creados</span><strong>{campaigns.length}</strong><small><em>En tu espacio</em></small></article></section>{campaigns.length ? <section className="panel recent-panel"><div className="panel-head"><div><span className="eyebrow">Tus coleccionables</span><h3>Actividad reciente</h3></div><button className="ghost-button" onClick={() => onNavigate("campaigns")}>Ver todos <ArrowRight size={15} /></button></div><CampaignTable campaigns={campaigns.slice(0, 3)} onManage={onManage} /></section> : <section className="panel empty-state"><Sparkles /><h3>Crea tu primer coleccionable</h3><p>Define la experiencia, diseña su Pill y envíala a revisión.</p><button className="primary-button" onClick={onCreate}>Crear coleccionable <ArrowRight size={17} /></button></section>}</>;
}
function Campaigns({ campaigns, onCreate, onManage }: { campaigns: Campaign[]; onCreate: () => void; onManage: (campaign: Campaign) => void }) { return <section><div className="page-intro"><div><span className="section-kicker"><span /> COLECCIONABLES</span><h2>Crea experiencias<br />que continúan.</h2><p>Los borradores quedan guardados y cada solicitud pasa por curaduría antes de habilitar su distribución.</p></div><button className="primary-button primary-large" onClick={onCreate}><Plus size={18} />Crear coleccionable</button></div>{campaigns.length ? <div className="campaign-card-grid">{campaigns.map((campaign) => <article className="campaign-card" key={campaign.id}><div className="campaign-art-wrap"><PillArtwork campaign={campaign} /><span className={`status ${statusClass(campaign.status)}`}><i />{campaign.status}</span></div><div className="campaign-card-copy"><span>{campaign.eventType} · {campaign.venue}</span><h3>{campaign.name}</h3><small><CalendarDays size={14} />{formatDate(campaign.startsAt)} — {formatDate(campaign.endsAt)}</small><small>Distribución: {[campaign.qrEnabled && "QR", campaign.secretEnabled && "Palabra secreta"].filter(Boolean).join(" + ")}</small><div><span><strong>{formatNumber(campaign.claimed)}</strong> coleccionadas</span><span><strong>{campaign.editable ? "Editable" : "Bloqueado"}</strong> contenido</span></div><button onClick={() => onManage(campaign)}>Gestionar coleccionable <ArrowRight size={16} /></button></div></article>)}</div> : <div className="empty-state"><Sparkles /><h3>Aún no tienes coleccionables</h3><p>Crea el primero para comenzar tu historia.</p><button className="primary-button" onClick={onCreate}>Crear coleccionable</button></div>}</section>; }
function CampaignTable({ campaigns, onManage }: { campaigns: Campaign[]; onManage: (campaign: Campaign) => void }) { return <div className="campaign-table">{campaigns.map((campaign) => <div className="campaign-row" key={campaign.id}><PillArtwork campaign={campaign} /><div className="campaign-name"><strong>{campaign.name}</strong><span>{campaign.eventType} · {campaign.venue}</span></div><div className="table-stat"><span>Estado</span><strong className={`status ${statusClass(campaign.status)}`}><i />{campaign.status}</strong></div><div className="table-stat"><span>Coleccionadas</span><strong>{formatNumber(campaign.claimed)} <small>/ {formatNumber(campaign.total)}</small></strong></div><div className="mini-progress"><i style={{ width: `${campaign.total ? (campaign.claimed / campaign.total) * 100 : 0}%` }} /></div><button className="icon-button" onClick={() => onManage(campaign)}><MoreHorizontal size={18} /></button></div>)}</div>; }

function ManageCampaign({ campaign, onClose, onSaved }: { campaign: Campaign; onClose: () => void; onSaved: (campaign: Campaign) => void }) {
  const [name, setName] = useState(campaign.name); const [description, setDescription] = useState(campaign.description); const [collaborator, setCollaborator] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [qr, setQr] = useState("");
  useEffect(() => { if (!campaign.qrToken || typeof window === "undefined") return; const fansUrl = process.env.NEXT_PUBLIC_PILLSFANS_URL || window.location.origin; void QRCode.toDataURL(`${fansUrl}/claim/${campaign.qrToken}`, { width: 280, margin: 1, color: { dark: "#181816", light: "#ffffff" } }).then(setQr); }, [campaign.qrToken]);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch(`/api/collectibles/${campaign.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description }) }); const result = await response.json(); setSaving(false); if (response.ok) onSaved({ ...campaign, ...result.collectible }); else setMessage(result.error); }
  async function addCollaborator() { setMessage(""); const response = await fetch(`/api/collectibles/${campaign.id}/collaborators`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: collaborator }) }); const result = await response.json(); if (response.ok) { const updated = { ...campaign, collaborators: [...campaign.collaborators, result.username] }; onSaved(updated); setCollaborator(""); setMessage(`@${result.username} ahora colabora en este coleccionable.`); } else setMessage(result.error); }
  return <div className="modal-backdrop"><div className="modal manage-modal"><div className="modal-head"><div><span className="section-kicker"><span /> GESTIONAR</span><h2>{campaign.name}</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><div className="manage-layout"><section><form onSubmit={save}><label><span>Título</span><input value={name} onChange={(event) => setName(event.target.value)} disabled={!campaign.editable} maxLength={150} /></label><label><span>Descripción</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} disabled={!campaign.editable} maxLength={1500} /></label>{campaign.editable ? <p className="edit-rule"><Check />Puedes editar título y descripción hasta la primera colección.</p> : <p className="edit-rule locked"><LockKeyhole />La primera Pill ya fue coleccionada. El contenido quedó bloqueado.</p>}<button className="primary-button" disabled={!campaign.editable || saving}>{saving ? "Guardando…" : "Guardar cambios"}</button></form><div className="collaborator-box"><span className="field-title">Colaboradores</span><p>Agrega a alguien por su nombre de usuario para que pueda continuar la gestión.</p><div><input value={collaborator} onChange={(event) => setCollaborator(event.target.value)} placeholder="@usuario" /><button className="secondary-button" onClick={addCollaborator}><UserPlus size={16} />Agregar</button></div>{campaign.collaborators.length > 0 && <small>{campaign.collaborators.map((item) => `@${item}`).join(", ")}</small>}</div>{message && <p className="form-error">{message}</p>}</section><aside className="distribution-card"><span className={`status ${statusClass(campaign.status)}`}><i />{campaign.status}</span>{campaign.reviewStatus === "approved" ? <>{campaign.qrEnabled && campaign.qrToken && <div className="qr-preview">{qr ? <Image src={qr} alt="Código QR del coleccionable" width={210} height={210} unoptimized /> : <QrCode />}<strong>QR listo para compartir</strong><a download={`${campaign.name}-qr.png`} href={qr}>Descargar QR</a></div>}{campaign.secretEnabled && <div className="secret-ready"><ShieldCheck /><span><strong>Frase secreta habilitada</strong><small>Funcionará durante las fechas del evento.</small></span></div>}</> : <div className="pending-distribution"><ShieldCheck /><h3>Distribución bloqueada</h3><p>El QR y la frase secreta se habilitan cuando Curaduría aprueba la solicitud.</p></div>}</aside></div></div></div>;
}

function Moderation({ onChanged }: { onChanged: () => void }) {
  const [items, setItems] = useState<Campaign[]>([]); const [selected, setSelected] = useState<Campaign | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/collectibles", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (response.ok) setItems(result.collectibles); else setMessage(result.error); });
  useEffect(() => { void load(); }, []);
  async function review(decision: "approved" | "rejected") { if (!selected) return; const response = await fetch(`/api/admin/collectibles/${selected.id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, reason }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error); return; } setSelected(null); setReason(""); await load(); onChanged(); }
  const pending = items.filter((item) => item.reviewStatus === "pending");
  return <section><div className="page-intro"><div><span className="section-kicker"><span /> SUPER ADMIN</span><h2>Curaduría de<br />coleccionables.</h2><p>Revisa identidad, contexto, derechos del arte y seguridad antes de habilitar la distribución.</p></div></div><div className="moderation-summary"><article><strong>{pending.length}</strong><span>Pendientes</span></article><article><strong>{items.filter((item) => item.reviewStatus === "approved").length}</strong><span>Aprobados</span></article><article><strong>{items.filter((item) => item.reviewStatus === "rejected").length}</strong><span>Rechazados</span></article></div><div className="safety-rules"><ShieldCheck /><div><strong>Control rápido de seguridad</strong><p>Rechaza pornografía o sexualización de menores, violencia gráfica o celebratoria, odio o acoso, fraude o suplantación, actividades ilegales y uso de arte sin derechos.</p></div></div>{message && <p className="form-error">{message}</p>}<div className="review-list">{pending.map((item) => <article key={item.id}><PillArtwork campaign={item} /><div><span>{item.eventType} · {item.venue}</span><h3>{item.name}</h3><p>{item.description}</p><small>Enviada {formatDate(item.createdAt)}</small></div><button className="primary-button" onClick={() => setSelected(item)}>Revisar</button></article>)}{!pending.length && <div className="empty-state"><BadgeCheck /><h3>La cola está al día</h3><p>No hay solicitudes pendientes.</p></div>}</div>{selected && <div className="modal-backdrop"><div className="modal review-modal"><div className="modal-head"><div><span className="section-kicker"><span /> REVISIÓN</span><h2>{selected.name}</h2></div><button className="icon-button" onClick={() => setSelected(null)}><X /></button></div><div className="review-content"><div className="review-art"><PillArtwork campaign={selected} /></div><p>{selected.description}</p><ul><li><Check />El evento y el creador son identificables.</li><li><Check />El arte no infringe derechos evidentes.</li><li><Check />No contiene pornografía, odio ni violencia gráfica.</li><li><Check />No promueve fraude, engaño o actividades ilegales.</li></ul><label><span>Motivo si rechazas</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explica qué debe corregir el creador" /></label><div className="modal-actions"><button className="secondary-button danger-button" onClick={() => void review("rejected")}>Rechazar</button><button className="primary-button" onClick={() => void review("approved")}><BadgeCheck size={16} />Aprobar y habilitar distribución</button></div></div></div></div>}</section>;
}

function Collections({ campaigns }: { campaigns: Campaign[] }) { return <section><div className="page-intro"><div><span className="section-kicker"><span /> COLECCIONES</span><h2>Una historia puede tener<br />muchas Pills.</h2><p>Agrupa tus coleccionables en listas.</p></div></div>{campaigns.length ? <div className="collection-grid"><article className="new-collection"><span><Plus /></span><h3>Crea una nueva colección</h3><p>Reúne tus coleccionables bajo una misma historia.</p><button>Comenzar</button></article></div> : <div className="empty-state"><FolderHeart /><h3>Aún no tienes colecciones</h3></div>}</section>; }
function Verification() { return <section><div className="page-intro"><div><span className="section-kicker"><span /> CONFIANZA</span><h2>Tu identidad,<br />reconocida.</h2><p>Podrás solicitar verificación como creador, marca, artista o equipo.</p></div></div><div className="verification-grid"><article className="panel verify-card"><div className="verify-hero"><span className="avatar avatar-orange">P</span></div><span className="status"><i />Sin verificar</span><h3>Cuenta personal</h3><p>La verificación pública será parte de una siguiente etapa.</p></article><article className="panel verify-info"><span className="eyebrow">CURADURÍA PILLS</span><h3>Cada publicación pasa por revisión</h3><div><span><BadgeCheck /></span><p><strong>Experiencia oficial</strong>Identifica coleccionables aprobados y habilita su distribución.</p></div><div><span><TicketCheck /></span><p><strong>Comunidad protegida</strong>Aplicamos reglas sobre seguridad, derechos y contenido.</p></div></article></div></section>; }
function Profile({ profile, onSaved }: { profile: CreatorProfile; onSaved: (profile: CreatorProfile) => void }) { const [form, setForm] = useState(profile); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/profile/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (response.ok) { onSaved(form); setMessage("Perfil actualizado"); } else setMessage(result.error || "No pudimos guardar tu perfil"); setSaving(false); } return <section><div className="page-intro"><div><span className="section-kicker"><span /> MI PERFIL</span><h2>Así te verá<br />la comunidad.</h2><p>Tu correo permanece privado.</p></div></div><form className="panel profile-form" onSubmit={save}><label>Nombre de usuario <strong>Obligatorio</strong></label><div className="username-field"><span>@</span><input required minLength={3} maxLength={24} value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value.toLowerCase().replace(/[^a-z0-9._]/g, "") })} /></div><div className="optional-label"><span>Información personal</span><em>Opcional</em></div><div className="profile-grid"><label><span>Nombre</span><div><input value={form.firstName} onChange={(event) => setForm({ ...form, firstName: event.target.value })} /></div></label><label><span>Apellido</span><div><input value={form.lastName} onChange={(event) => setForm({ ...form, lastName: event.target.value })} /></div></label></div><label className="bio-label">Descripción breve</label><textarea maxLength={180} value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} />{message && <p>{message}</p>}<button className="primary-button onboarding-submit" disabled={saving}>{saving ? "Guardando…" : "Guardar perfil"}</button></form></section>; }

function CreateCampaign({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<void> }) {
  const [preview, setPreview] = useState(""); const [step, setStep] = useState(1); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  async function selectArtwork(file?: File) { if (preview) URL.revokeObjectURL(preview); setError(""); setPreview(""); if (!file) return; if (file.size > 5 * 1024 * 1024) { setError("La imagen debe pesar menos de 5 MB."); return; } try { const bitmap = await createImageBitmap(file); const square = bitmap.width === bitmap.height; bitmap.close(); if (!square) { setError("El arte debe ser cuadrado, con proporción 1:1."); return; } } catch { setError("No pudimos leer esta imagen."); return; } setPreview(URL.createObjectURL(file)); }
  function goNext() { const data = new FormData(formRef.current!); setError(""); if (step === 1 && (!preview || !String(data.get("name") || "").trim() || !String(data.get("description") || "").trim() || !data.get("date") || !data.get("endDate"))) { setError("Agrega el arte, nombre, descripción y ambas fechas."); return; } if (step === 1 && String(data.get("endDate")) <= String(data.get("date"))) { setError("La fecha de término debe ser posterior a la fecha de inicio."); return; } setStep((current) => Math.min(4, current + 1)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const qr = data.get("distributionQr"); const secret = data.get("distributionSecret"); if (!qr && !secret) { setError("Selecciona QR, palabra secreta o ambos métodos."); return; } if (secret && !String(data.get("secretWord") || "").trim()) { setError("Escribe la palabra secreta."); return; } setSaving(true); setError(""); try { await onSubmit(event); } catch (cause) { setError(cause instanceof Error ? cause.message : "No pudimos guardar el coleccionable."); setSaving(false); } }
  const steps = [{ title: "Detalles", note: "Arte, nombre y contexto" }, { title: "Propiedades", note: "Información y equipo" }, { title: "Emisión", note: "Cantidad y acceso" }, { title: "Distribución", note: "Métodos tras aprobación" }];
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal collectible-modal wizard-modal"><aside className="wizard-sidebar"><span className="eyebrow">NUEVO COLECCIONABLE</span><h3>Solicitud</h3><p>Completa cada paso y envía tu Pill a curaduría.</p><nav>{steps.map((item, index) => <button type="button" key={item.title} className={`${step === index + 1 ? "active" : ""} ${step > index + 1 ? "complete" : ""}`} onClick={() => setStep(index + 1)}><i>{step > index + 1 ? <Check /> : index + 1}</i><span><strong>{item.title}</strong><small>{item.note}</small></span></button>)}</nav></aside><form ref={formRef} className="wizard-main" onSubmit={submit}><div className="modal-head"><div><span className="section-kicker"><span /> PASO {step} DE 4</span><h2>{steps[step - 1].title}</h2></div><button type="button" className="icon-button" onClick={onClose}><X /></button></div>
    <div className={`wizard-panel ${step === 1 ? "active" : ""}`}><div className="collectible-form"><div className="artwork-column"><span className="field-title">Arte del coleccionable *</span><label className={`artwork-uploader ${preview ? "has-artwork" : ""}`}><input name="artwork" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(event) => void selectArtwork(event.target.files?.[0])} />{preview ? <span className="artwork-preview" style={{ backgroundImage: `url(${preview})` }} /> : <><span className="upload-icon"><ImagePlus /></span><strong>Cargar insignia</strong><small>Cuadrada, proporción 1:1</small><small>Máximo 5 MB</small></>}</label><p>PNG, JPG, WEBP o GIF. Recomendado: 500 × 500 px.</p></div><div className="collectible-fields"><label><span>Nombre *</span><input name="name" maxLength={150} placeholder="Ej. Una noche en el Nacional" autoFocus /></label><label><span>Descripción *</span><textarea name="description" maxLength={1500} placeholder="¿Qué hace especial a esta experiencia?" /></label><div className="form-grid"><label><span>Fecha de inicio *</span><input name="date" type="date" /></label><label><span>Fecha de término *</span><input name="endDate" type="date" /></label></div><label><span>URL del evento</span><input name="eventUrl" type="url" placeholder="https://" /></label></div></div></div>
    <div className={`wizard-panel ${step === 2 ? "active" : ""}`}><div className="wizard-fields"><label><span>Tipo de evento</span><select name="type" defaultValue="Concierto"><option>Concierto</option><option>Fútbol</option><option>Festival</option><option>Cultura</option><option>Marca</option><option>Comunidad</option></select></label><label><span>Lugar</span><input name="location" placeholder="Ej. Estadio Nacional, Santiago" /></label><label><span>Etiquetas</span><input name="tags" placeholder="música, santiago, comunidad" /></label><label><span>Colaborador inicial</span><input name="collaborator" placeholder="@nombredeusuario" /></label><div className="form-note"><UserPlus /><p><strong>Equipo de respaldo.</strong> El colaborador podrá gestionar el coleccionable si la persona creadora no está disponible.</p></div></div></div>
    <div className={`wizard-panel ${step === 3 ? "active" : ""}`}><div className="wizard-fields"><label><span>Cantidad disponible</span><input name="supply" type="number" min="1" max="1000000" defaultValue="5000" /></label><label><span>Quién puede coleccionarla</span><select name="audience" defaultValue="Asistentes"><option>Asistentes</option><option>Cualquier persona</option><option>Solo invitados</option></select></label><div className="form-note"><LockKeyhole /><p><strong>Contenido fijo después de la primera colección.</strong> Antes puedes editar título y descripción. El arte, fechas y emisión quedan fijos al enviar.</p></div></div></div>
    <div className={`wizard-panel ${step === 4 ? "active" : ""}`}><div className="wizard-fields"><span className="field-title">Métodos solicitados *</span><div className="distribution-options"><label><input type="checkbox" name="distributionQr" defaultChecked /><span><strong>Código QR</strong><small>Se genera solo después de la aprobación.</small></span></label><label><input type="checkbox" name="distributionSecret" /><span><strong>Palabra secreta</strong><small>Se habilita solo después de la aprobación.</small></span></label></div><label><span>Palabra secreta</span><input name="secretWord" maxLength={60} placeholder="Ej. PILLS2026" /></label><div className="expiration-rule"><CalendarDays /><p><strong>Vigencia automática</strong>Los métodos funcionarán entre la fecha de inicio y la fecha de término.</p></div><div className="admin-link-rule"><ShieldCheck /><p><strong>Revisión de comunidad</strong>Curaduría verificará seguridad, contexto, derechos del arte y autenticidad antes de habilitar la distribución.</p></div></div></div>
    {error && <p className="wizard-error">{error}</p>}<div className="modal-actions wizard-actions"><button type="button" className="secondary-button" onClick={step === 1 ? onClose : () => { setError(""); setStep((current) => current - 1); }}>{step === 1 ? "Cancelar" : "Atrás"}</button>{step < 4 ? <button className="primary-button" type="button" onClick={goNext}>Continuar <ArrowRight size={17} /></button> : <button className="primary-button" type="submit" disabled={saving}>{saving ? "Guardando…" : <>Enviar a curaduría <ArrowRight size={17} /></>}</button>}</div></form></div></div>;
}
