"use client";

import { BadgeCheck, Building2, ExternalLink, Search, ShieldCheck, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type Organization = { id: string; name: string; username: string; description: string; websiteUrl: string; status: "pending" | "approved" | "rejected"; evidence: string; rejectionReason: string; submittedAt: string | null; owner: string };
export function AdminOrganizationsPanel() {
  const [items, setItems] = useState<Organization[]>([]); const [selected, setSelected] = useState<Organization | null>(null); const [filter, setFilter] = useState<"all" | Organization["status"]>("pending"); const [query, setQuery] = useState(""); const [reason, setReason] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/admin/organizations", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result.organizations); setSelected((current) => current ? result.organizations.find((item: Organization) => item.id === current.id) ?? null : null); } catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos cargar las solicitudes."); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; fetch("/api/admin/organizations", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) setItems(result.organizations); }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : "No pudimos cargar las solicitudes."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const visible = useMemo(() => items.filter((item) => (filter === "all" || item.status === filter) && `${item.name} ${item.username} ${item.owner}`.toLowerCase().includes(query.toLowerCase())), [filter, items, query]);
  async function decide(decision: "approved" | "rejected") { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch(`/api/admin/organizations/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, reason }) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } setReason(""); await load(); }
  return <section><div className="page-intro"><div><span className="section-kicker"><span /> VERIFICACIÓN</span><h2>Organizaciones<br />oficiales.</h2><p>Comprueba el vínculo del solicitante antes de activar el @ público de una organización.</p></div></div><div className="organization-review-summary"><article><strong>{items.filter((item) => item.status === "pending").length}</strong><span>Pendientes</span></article><article><strong>{items.filter((item) => item.status === "approved").length}</strong><span>Aprobadas</span></article><article><strong>{items.filter((item) => item.status === "rejected").length}</strong><span>Rechazadas</span></article></div><div className="user-admin-toolbar"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar organización o propietario" /></label><div>{(["pending","approved","rejected","all"] as const).map((value) => <button className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)}>{value === "pending" ? "Pendientes" : value === "approved" ? "Aprobadas" : value === "rejected" ? "Rechazadas" : "Todas"}</button>)}</div></div>{message && <p className="form-error">{message}</p>}<div className="organization-review-list">{visible.map((item) => <button key={item.id} onClick={() => { setSelected(item); setReason(""); setMessage(""); }}><span className="organization-avatar">{item.name.slice(0,2).toUpperCase()}</span><div><span className={`organization-status ${item.status}`}>{item.status === "pending" ? "En revisión" : item.status === "approved" ? "Aprobada" : "Rechazada"}</span><h3>{item.name}</h3><strong>@{item.username} · solicitada por @{item.owner}</strong></div><BadgeCheck /></button>)}{!loading && !visible.length && <div className="empty-state"><Building2 /><h3>No hay solicitudes en este estado</h3></div>}</div>
    {selected && <div className="modal-backdrop"><div className="modal organization-review-modal"><div className="modal-head"><div><span className="section-kicker"><span /> SOLICITUD DE ORGANIZACIÓN</span><h2>{selected.name}</h2><small>@{selected.username} · @{selected.owner}</small></div><button className="icon-button" onClick={() => setSelected(null)}><X /></button></div><div className="organization-review-content"><div className="organization-review-identity"><span className="organization-avatar">{selected.name.slice(0,2).toUpperCase()}</span><div><strong>{selected.name}</strong><span>@{selected.username}</span></div></div><section><h3>Descripción</h3><p>{selected.description || "Sin descripción."}</p></section><section><h3>Antecedentes del vínculo</h3><p>{selected.evidence}</p></section>{selected.websiteUrl && <a href={selected.websiteUrl} target="_blank" rel="noreferrer"><ExternalLink />{selected.websiteUrl}</a>}{selected.status === "pending" ? <><label><span>Motivo si se rechaza</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explica qué falta o qué debe corregirse" /></label><div className="modal-actions"><button className="secondary-button danger-button" disabled={saving} onClick={() => void decide("rejected")}>Rechazar</button><button className="primary-button" disabled={saving} onClick={() => void decide("approved")}><ShieldCheck />Aprobar organización</button></div></> : <div className={`organization-decision ${selected.status}`}><strong>{selected.status === "approved" ? "Organización aprobada" : "Solicitud rechazada"}</strong>{selected.rejectionReason && <p>{selected.rejectionReason}</p>}</div>}{message && <p className="form-error">{message}</p>}</div></div></div>}
  </section>;
}
