"use client";

import { ArrowRight, FolderHeart, Image as ImageIcon, Plus, Trash2, UserPlus, Users, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Pill = { id: string; collectionId?: string | null; name: string; imageUrl: string; creator?: string; createdBy?: string; reviewStatus?: string; canRemove?: boolean };
type Contributor = { userId: string; username: string; role: "contributor" };
type Collection = { id: string; name: string; description: string; createdAt: string; isOwner: boolean; owner: string; pills: Pill[]; contributors: Contributor[] };

export function CollectionsPanel() {
  const [collections, setCollections] = useState<Collection[]>([]); const [ownPills, setOwnPills] = useState<Pill[]>([]);
  const [selected, setSelected] = useState<Collection | null>(null); const [creating, setCreating] = useState(false);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => {
    try { const response = await fetch("/api/collections", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCollections(result.collections); setOwnPills(result.ownPills); setSelected((current) => current ? result.collections.find((item: Collection) => item.id === current.id) ?? null : null); }
    catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos cargar tus colecciones."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { let active = true; fetch("/api/collections", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) { setCollections(result.collections); setOwnPills(result.ownPills); } }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : "No pudimos cargar tus colecciones."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const availablePills = useMemo(() => ownPills.filter((pill) => !pill.collectionId), [ownPills]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/collections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), description: form.get("description") }) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } setCreating(false); await load(); }
  async function act(action: string, payload: Record<string, unknown> = {}) { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch(`/api/collections/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } await load(); }
  async function removeCollection() { if (!selected || !window.confirm("¿Eliminar esta colección? Las Pills quedarán disponibles para agregarlas a otra colección.")) return; setSaving(true); const response = await fetch(`/api/collections/${selected.id}`, { method: "DELETE" }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } setSelected(null); await load(); }
  return <section><div className="page-intro"><div><span className="section-kicker"><span /> COLECCIONES</span><h2>Una historia puede tener<br />muchas Pills.</h2><p>Crea una colección después de tu primera Pill e invita a otros creadores para sumar las suyas.</p></div><button className="primary-button primary-large" disabled={!ownPills.length} onClick={() => setCreating(true)}><Plus />Nueva colección</button></div>
    <div className="collection-flow"><article><span>1</span><div><strong>Crea una Pill</strong><p>Cada Pill mantiene a su creador original.</p></div></article><ArrowRight /><article><span>2</span><div><strong>Abre una colección</strong><p>No requiere verificación.</p></div></article><ArrowRight /><article><span>3</span><div><strong>Invita creadores</strong><p>Cada invitado suma solo sus propias Pills.</p></div></article></div>
    {message && <p className="form-error">{message}</p>}
    {!loading && !ownPills.length ? <div className="empty-state collection-empty"><FolderHeart /><h3>Primero crea una Pill</h3><p>Cuando tengas una, podrás crear una colección y comenzar a reunir una historia.</p></div> : <div className="collection-cards">{collections.map((collection) => <button key={collection.id} onClick={() => { setSelected(collection); setMessage(""); }}><div className="collection-cover">{collection.pills.slice(0, 3).map((pill) => pill.imageUrl ? <span key={pill.id} style={{ backgroundImage: `url(${pill.imageUrl})` }} /> : <span key={pill.id}><ImageIcon /></span>)}{!collection.pills.length && <FolderHeart />}</div><div className="collection-card-copy"><span>{collection.isOwner ? "Tu colección" : `Invitación de @${collection.owner}`}</span><h3>{collection.name}</h3><p>{collection.description || "Una colección de Pills."}</p><footer><b>{collection.pills.length} Pills</b><b><Users />{collection.contributors.length + 1} creadores</b></footer></div></button>)}{Boolean(ownPills.length) && <button className="collection-create-card" onClick={() => setCreating(true)}><Plus /><strong>Nueva colección</strong><span>Agrupa Pills bajo una misma historia</span></button>}</div>}
    {creating && <div className="modal-backdrop"><div className="modal collection-modal"><div className="modal-head"><div><span className="section-kicker"><span /> NUEVA COLECCIÓN</span><h2>Crea una historia</h2></div><button className="icon-button" onClick={() => setCreating(false)}><X /></button></div><form onSubmit={create}><label><span>Nombre *</span><input name="name" required minLength={2} maxLength={120} placeholder="Ej. Temporada 2026" /></label><label><span>Descripción</span><textarea name="description" maxLength={600} placeholder="¿Qué conecta a estas Pills?" /></label><p className="form-note"><FolderHeart />La colección se crea sin revisión. Después podrás agregar tus Pills e invitar a otros creadores.</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setCreating(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Creando…" : "Crear colección"}</button></div></form></div></div>}
    {selected && <div className="modal-backdrop collection-manage-backdrop"><div className="modal collection-manage-modal"><div className="modal-head"><div><span className="section-kicker"><span /> GESTIONAR COLECCIÓN</span><h2>{selected.name}</h2><small>Creada por @{selected.owner}</small></div><button className="icon-button" onClick={() => setSelected(null)}><X /></button></div><div className="collection-manage-scroll">
      {selected.isOwner && <form className="collection-edit" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("update", { name: form.get("name"), description: form.get("description") }); }}><label><span>Nombre</span><input name="name" defaultValue={selected.name} /></label><label><span>Descripción</span><textarea name="description" defaultValue={selected.description} /></label><button className="secondary-button" disabled={saving}>Guardar información</button></form>}
      <div className="collection-manage-grid"><section><h3>Pills de la colección</h3><p>Cada creador conserva el control de su Pill.</p><div className="collection-pill-list">{selected.pills.map((pill) => <article key={pill.id}>{pill.imageUrl ? <span style={{ backgroundImage: `url(${pill.imageUrl})` }} /> : <span><ImageIcon /></span>}<div><strong>{pill.name}</strong><small>por @{pill.creator}</small></div>{pill.canRemove && <button aria-label="Quitar Pill" disabled={saving} onClick={() => void act("remove_pill", { pillId: pill.id })}><X /></button>}</article>)}{!selected.pills.length && <em>Aún no hay Pills en esta colección.</em>}</div>{availablePills.length > 0 && <form className="inline-add" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("add_pill", { pillId: form.get("pillId") }); }}><select name="pillId" required defaultValue=""><option value="" disabled>Selecciona una Pill creada por ti</option>{availablePills.map((pill) => <option key={pill.id} value={pill.id}>{pill.name}</option>)}</select><button className="primary-button" disabled={saving}><Plus />Agregar</button></form>}</section><section><h3>Creadores con permiso</h3><p>Pueden sumar sus propias Pills; no pueden editar ni eliminar la colección.</p><div className="collection-people">{selected.contributors.map((person) => <article key={person.userId}><span>{person.username.slice(0, 2).toUpperCase()}</span><strong>@{person.username}</strong>{selected.isOwner && <button onClick={() => void act("remove_contributor", { userId: person.userId })}><X /></button>}</article>)}{!selected.contributors.length && <em>No hay otros creadores.</em>}</div>{selected.isOwner && <form className="inline-add" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("add_contributor", { username: form.get("username") }); event.currentTarget.reset(); }}><input name="username" required placeholder="@usuario" /><button className="primary-button" disabled={saving}><UserPlus />Invitar</button></form>}</section></div>
      {message && <p className="form-error">{message}</p>}{selected.isOwner && <div className="collection-danger"><div><strong>Eliminar colección</strong><p>Las Pills no se eliminan; vuelven a quedar sin colección.</p></div><button className="secondary-button danger-button" disabled={saving} onClick={() => void removeCollection()}><Trash2 />Eliminar</button></div>}
    </div></div></div>}
  </section>;
}
