"use client";

import { BadgeCheck, Building2, ExternalLink, Plus, ShieldCheck, UserPlus, Users, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Member = { userId: string; username: string; role: "owner" | "admin" | "editor" };
type Organization = { id: string; name: string; username: string; description: string; websiteUrl: string; status: "pending" | "approved" | "rejected"; evidence: string; rejectionReason: string; role: Member["role"]; members: Member[] };
const statusLabel = { pending: "En revisión", approved: "Organización oficial", rejected: "Requiere cambios" };

export function OrganizationsPanel() {
  const [organizations, setOrganizations] = useState<Organization[]>([]); const [selected, setSelected] = useState<Organization | null>(null);
  const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/organizations", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setOrganizations(result.organizations); setSelected((current) => current ? result.organizations.find((item: Organization) => item.id === current.id) ?? null : null); } catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos cargar tus organizaciones."); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; fetch("/api/organizations", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) setOrganizations(result.organizations); }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : "No pudimos cargar tus organizaciones."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/organizations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } setCreating(false); await load(); }
  async function act(action: string, payload: Record<string, unknown> = {}) { if (!selected) return; setSaving(true); setMessage(""); const response = await fetch(`/api/organizations/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await response.json(); setSaving(false); if (!response.ok) { setMessage(result.error); return; } await load(); }
  return <section><div className="page-intro"><div><span className="section-kicker"><span /> ORGANIZACIONES</span><h2>Una identidad<br />para crear en equipo.</h2><p>Solicita el @ oficial de una organización y acredita tu vínculo. Las colecciones personales no necesitan esta verificación.</p></div><button className="primary-button primary-large" onClick={() => setCreating(true)}><Plus />Postular organización</button></div>
    <div className="organization-explainer"><ShieldCheck /><div><strong>¿Qué se verifica?</strong><p>Revisamos que representes o estés vinculado a la organización antes de activar su perfil oficial. El @ queda reservado desde que envías la solicitud.</p></div></div>
    {message && <p className="form-error">{message}</p>}<div className="organization-grid">{organizations.map((organization) => <button key={organization.id} onClick={() => { setSelected(organization); setMessage(""); }}><span className="organization-avatar">{organization.name.slice(0, 2).toUpperCase()}</span><div><span className={`organization-status ${organization.status}`}>{organization.status === "approved" && <BadgeCheck />}{statusLabel[organization.status]}</span><h3>{organization.name}</h3><strong>@{organization.username}</strong><p>{organization.description || "Perfil de organización"}</p><small><Users />{organization.members.length} personas</small></div></button>)}{!loading && !organizations.length && <div className="empty-state"><Building2 /><h3>Aún no administras organizaciones</h3><p>Postula una cuando necesites crear bajo una identidad oficial.</p></div>}</div>
    {creating && <div className="modal-backdrop"><div className="modal organization-modal"><div className="modal-head"><div><span className="section-kicker"><span /> SOLICITUD</span><h2>Postula una organización</h2></div><button className="icon-button" onClick={() => setCreating(false)}><X /></button></div><form onSubmit={create}><div className="form-grid"><label><span>Nombre *</span><input name="name" required placeholder="Nombre legal o público" /></label><label><span>@ de la organización *</span><input name="username" required pattern="[a-zA-Z0-9._]{3,24}" placeholder="@organizacion" /></label></div><label><span>Descripción</span><textarea name="description" maxLength={600} placeholder="Qué hace la organización" /></label><label><span>Sitio web</span><input name="website" placeholder="organizacion.com" /></label><label><span>Prueba de vínculo *</span><textarea name="evidence" required minLength={10} maxLength={1500} placeholder="Explica tu rol y agrega enlaces o antecedentes para verificarlo." /></label><p className="form-note"><ShieldCheck />El perfil quedará en revisión. Podrás administrarlo y sumar miembros, pero será público solo después de aprobarse.</p><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setCreating(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Enviando…" : "Enviar solicitud"}</button></div></form></div></div>}
    {selected && <div className="modal-backdrop collection-manage-backdrop"><div className="modal organization-manage-modal"><div className="modal-head"><div><span className={`organization-status ${selected.status}`}>{statusLabel[selected.status]}</span><h2>{selected.name}</h2><small>@{selected.username} · Tu rol: {selected.role}</small></div><button className="icon-button" onClick={() => setSelected(null)}><X /></button></div><div className="organization-manage-scroll">{selected.status === "rejected" && <div className="organization-rejection"><strong>La solicitud necesita cambios</strong><p>{selected.rejectionReason}</p><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("resubmit", { evidence: form.get("evidence") }); }}><textarea name="evidence" defaultValue={selected.evidence} minLength={10} required /><button className="primary-button" disabled={saving}>Reenviar a revisión</button></form></div>}
      <form className="organization-profile-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("update", { description: form.get("description"), website: form.get("website") }); }}><label><span>Descripción</span><textarea name="description" defaultValue={selected.description} /></label><label><span>Sitio web</span><input name="website" defaultValue={selected.websiteUrl} /></label><button className="secondary-button" disabled={saving}>Guardar perfil</button>{selected.websiteUrl && <a href={selected.websiteUrl} target="_blank" rel="noreferrer"><ExternalLink />Abrir sitio web</a>}</form>
      <section className="organization-members"><h3>Equipo de la organización</h3><p>Editor puede trabajar en el espacio. Admin también puede gestionar miembros.</p>{selected.members.map((member) => <article key={member.userId}><span>{member.username.slice(0, 2).toUpperCase()}</span><strong>@{member.username}</strong><em>{member.role === "owner" ? "Propietario" : member.role === "admin" ? "Admin" : "Editor"}</em>{member.role !== "owner" && ['owner','admin'].includes(selected.role) && <button onClick={() => void act("remove_member", { userId: member.userId })}><X /></button>}</article>)}{['owner','admin'].includes(selected.role) && <form className="organization-add-member" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act("add_member", { username: form.get("username"), role: form.get("role") }); event.currentTarget.reset(); }}><input name="username" required placeholder="@usuario" /><select name="role"><option value="editor">Editor</option>{selected.role === "owner" && <option value="admin">Admin</option>}</select><button className="primary-button" disabled={saving}><UserPlus />Agregar</button></form>}</section>{message && <p className="form-error">{message}</p>}
    </div></div></div>}
  </section>;
}
