export const CITY_OPTIONS = [
  // Chile
  "Santiago, Chile", "Valparaíso, Chile", "Viña del Mar, Chile", "Concón, Chile",
  "Quilpué, Chile", "Villa Alemana, Chile", "San Antonio, Chile", "Rancagua, Chile",
  "Machalí, Chile", "Talca, Chile", "Curicó, Chile", "Linares, Chile", "Chillán, Chile",
  "Concepción, Chile", "Talcahuano, Chile", "San Pedro de la Paz, Chile", "Los Ángeles, Chile",
  "Temuco, Chile", "Pucón, Chile", "Villarrica, Chile", "Valdivia, Chile", "Osorno, Chile",
  "Puerto Montt, Chile", "Puerto Varas, Chile", "Castro, Chile", "Ancud, Chile",
  "Coyhaique, Chile", "Punta Arenas, Chile", "Puerto Natales, Chile", "Arica, Chile",
  "Iquique, Chile", "Calama, Chile", "San Pedro de Atacama, Chile", "Antofagasta, Chile",
  "Copiapó, Chile", "La Serena, Chile", "Coquimbo, Chile", "Ovalle, Chile",
  "Alto Hospicio, Chile", "Tocopilla, Chile", "Mejillones, Chile", "Vallenar, Chile",
  "Caldera, Chile", "Illapel, Chile", "San Felipe, Chile",
  "Quillota, Chile", "Limache, Chile", "Melipilla, Chile", "Buin, Chile",
  "San Fernando, Chile", "Santa Cruz, Chile", "Constitución, Chile", "Cauquenes, Chile",
  "Parral, Chile", "Los Andes, Chile", "Coronel, Chile", "Lota, Chile", "Chiguayante, Chile",
  "Hualpén, Chile", "Tomé, Chile", "Penco, Chile", "Arauco, Chile", "Lebu, Chile",
  "Angol, Chile", "Victoria, Chile", "Nueva Imperial, Chile", "Loncoche, Chile",
  "La Unión, Chile", "Río Bueno, Chile", "Puerto Octay, Chile", "Frutillar, Chile",
  "Quellón, Chile", "Chaitén, Chile", "Puerto Aysén, Chile", "Porvenir, Chile",

  // Argentina y Uruguay
  "Buenos Aires, Argentina", "La Plata, Argentina", "Mar del Plata, Argentina",
  "Rosario, Argentina", "Córdoba, Argentina", "Mendoza, Argentina", "Salta, Argentina",
  "San Miguel de Tucumán, Argentina", "San Carlos de Bariloche, Argentina",
  "Ushuaia, Argentina", "Neuquén, Argentina", "Santa Fe, Argentina", "San Juan, Argentina",
  "San Salvador de Jujuy, Argentina", "Santiago del Estero, Argentina", "Catamarca, Argentina",
  "La Rioja, Argentina", "San Luis, Argentina", "Villa Mercedes, Argentina",
  "Río Cuarto, Argentina", "Villa Carlos Paz, Argentina", "Bahía Blanca, Argentina",
  "Tandil, Argentina", "Olavarría, Argentina", "San Nicolás de los Arroyos, Argentina",
  "Paraná, Argentina", "Concordia, Argentina", "Gualeguaychú, Argentina",
  "Posadas, Argentina", "Puerto Iguazú, Argentina", "Resistencia, Argentina",
  "Corrientes, Argentina", "Formosa, Argentina", "Rafaela, Argentina",
  "Venado Tuerto, Argentina", "Junín, Argentina", "Pergamino, Argentina",
  "Santa Rosa, Argentina", "General Roca, Argentina", "Cipolletti, Argentina",
  "San Martín de los Andes, Argentina", "Villa La Angostura, Argentina",
  "Puerto Madryn, Argentina", "Trelew, Argentina", "Comodoro Rivadavia, Argentina",
  "Río Gallegos, Argentina", "El Calafate, Argentina", "El Chaltén, Argentina",
  "Montevideo, Uruguay", "Punta del Este, Uruguay", "Maldonado, Uruguay",
  "Colonia del Sacramento, Uruguay", "Piriápolis, Uruguay", "Salto, Uruguay",
  "Ciudad de la Costa, Uruguay", "Canelones, Uruguay", "Las Piedras, Uruguay",
  "Paysandú, Uruguay", "Rivera, Uruguay", "Tacuarembó, Uruguay", "Melo, Uruguay",
  "Mercedes, Uruguay", "Fray Bentos, Uruguay", "Durazno, Uruguay", "Florida, Uruguay",
  "Minas, Uruguay", "Rocha, Uruguay", "La Paloma, Uruguay", "Chuy, Uruguay",

  // Perú, Bolivia, Paraguay y Ecuador
  "Lima, Perú", "Cusco, Perú", "Arequipa, Perú", "Trujillo, Perú", "Piura, Perú",
  "Chiclayo, Perú", "Iquitos, Perú", "Tacna, Perú", "La Paz, Bolivia",
  "Callao, Perú", "Chimbote, Perú", "Huancayo, Perú", "Ayacucho, Perú",
  "Cajamarca, Perú", "Huaraz, Perú", "Puno, Perú", "Juliaca, Perú", "Ica, Perú",
  "Pisco, Perú", "Tarapoto, Perú", "Pucallpa, Perú", "Puerto Maldonado, Perú",
  "Tumbes, Perú", "Moquegua, Perú", "Abancay, Perú", "Huánuco, Perú",
  "Santa Cruz de la Sierra, Bolivia", "Cochabamba, Bolivia", "Sucre, Bolivia",
  "El Alto, Bolivia", "Oruro, Bolivia", "Potosí, Bolivia", "Tarija, Bolivia",
  "Trinidad, Bolivia", "Cobija, Bolivia", "Sacaba, Bolivia", "Montero, Bolivia",
  "Asunción, Paraguay", "Ciudad del Este, Paraguay", "Encarnación, Paraguay",
  "San Lorenzo, Paraguay", "Luque, Paraguay", "Capiatá, Paraguay", "Lambaré, Paraguay",
  "Fernando de la Mora, Paraguay", "Mariano Roque Alonso, Paraguay", "Caaguazú, Paraguay",
  "Coronel Oviedo, Paraguay", "Pedro Juan Caballero, Paraguay", "Concepción, Paraguay",
  "Quito, Ecuador", "Guayaquil, Ecuador", "Cuenca, Ecuador", "Manta, Ecuador",
  "Baños de Agua Santa, Ecuador", "Loja, Ecuador",
  "Ambato, Ecuador", "Riobamba, Ecuador", "Machala, Ecuador", "Portoviejo, Ecuador",
  "Santo Domingo, Ecuador", "Ibarra, Ecuador", "Esmeraldas, Ecuador", "Quevedo, Ecuador",
  "Salinas, Ecuador", "Latacunga, Ecuador", "Tena, Ecuador", "Puyo, Ecuador",
  "Puerto Ayora, Ecuador", "Otavalo, Ecuador",

  // Colombia y Venezuela
  "Bogotá, Colombia", "Medellín, Colombia", "Cali, Colombia", "Cartagena, Colombia",
  "Barranquilla, Colombia", "Santa Marta, Colombia", "Bucaramanga, Colombia",
  "Pereira, Colombia", "Manizales, Colombia", "Armenia, Colombia", "Caracas, Venezuela",
  "Cúcuta, Colombia", "Ibagué, Colombia", "Villavicencio, Colombia", "Pasto, Colombia",
  "Neiva, Colombia", "Montería, Colombia", "Sincelejo, Colombia", "Valledupar, Colombia",
  "Tunja, Colombia", "Popayán, Colombia", "Riohacha, Colombia", "Quibdó, Colombia",
  "Yopal, Colombia", "Florencia, Colombia", "Buenaventura, Colombia", "Palmira, Colombia",
  "Barrancabermeja, Colombia", "San Andrés, Colombia", "Villa de Leyva, Colombia",
  "Maracaibo, Venezuela", "Valencia, Venezuela", "Barquisimeto, Venezuela",
  "Maracay, Venezuela", "Ciudad Guayana, Venezuela", "Barcelona, Venezuela",
  "Puerto La Cruz, Venezuela", "Maturín, Venezuela", "San Cristóbal, Venezuela",
  "Mérida, Venezuela", "Cumaná, Venezuela", "Coro, Venezuela", "Barinas, Venezuela",
  "Porlamar, Venezuela", "Los Teques, Venezuela", "Cabimas, Venezuela",

  // Brasil
  "São Paulo, Brasil", "Río de Janeiro, Brasil", "Brasilia, Brasil", "Belo Horizonte, Brasil",
  "Salvador, Brasil", "Recife, Brasil", "Fortaleza, Brasil", "Porto Alegre, Brasil",
  "Curitiba, Brasil", "Florianópolis, Brasil", "Manaos, Brasil", "Belém, Brasil",
  "Goiânia, Brasil", "Campinas, Brasil", "Foz do Iguaçu, Brasil",
  "São Luís, Brasil", "Maceió, Brasil", "Natal, Brasil", "João Pessoa, Brasil",
  "Aracaju, Brasil", "Teresina, Brasil", "Campo Grande, Brasil", "Cuiabá, Brasil",
  "Vitória, Brasil", "Palmas, Brasil", "Porto Velho, Brasil", "Rio Branco, Brasil",
  "Boa Vista, Brasil", "Macapá, Brasil", "Joinville, Brasil", "Blumenau, Brasil",
  "Balneário Camboriú, Brasil", "Gramado, Brasil", "Caxias do Sul, Brasil",
  "Pelotas, Brasil", "Londrina, Brasil", "Maringá, Brasil", "Cascavel, Brasil",
  "Santos, Brasil", "Guarulhos, Brasil", "Ribeirão Preto, Brasil", "Sorocaba, Brasil",
  "São José dos Campos, Brasil", "Niterói, Brasil", "Petrópolis, Brasil",
  "Juiz de Fora, Brasil", "Uberlândia, Brasil", "Ouro Preto, Brasil", "Ilhéus, Brasil",
  "Porto Seguro, Brasil", "Fernando de Noronha, Brasil",

  // Guyana, Surinam y Guayana Francesa
  "Georgetown, Guyana", "Linden, Guyana", "New Amsterdam, Guyana",
  "Paramaribo, Surinam", "Lelydorp, Surinam", "Nieuw Nickerie, Surinam",
  "Cayena, Guayana Francesa", "Kourou, Guayana Francesa", "Saint-Laurent-du-Maroni, Guayana Francesa",

  // México, Centroamérica y Caribe
  "Ciudad de México, México", "Guadalajara, México", "Monterrey, México", "Puebla, México",
  "Querétaro, México", "Mérida, México", "Cancún, México", "Tulum, México",
  "Playa del Carmen, México", "Oaxaca, México", "San Miguel de Allende, México",
  "Tijuana, México", "Ciudad de Guatemala, Guatemala", "Antigua Guatemala, Guatemala",
  "San Salvador, El Salvador", "Tegucigalpa, Honduras", "San Pedro Sula, Honduras",
  "Managua, Nicaragua", "San José, Costa Rica", "Ciudad de Panamá, Panamá",
  "La Habana, Cuba", "Santo Domingo, República Dominicana", "Punta Cana, República Dominicana",
  "San Juan, Puerto Rico", "Kingston, Jamaica",

  // Estados Unidos y Canadá
  "Miami, Estados Unidos", "Orlando, Estados Unidos", "Nueva York, Estados Unidos",
  "Los Ángeles, Estados Unidos", "San Francisco, Estados Unidos", "Las Vegas, Estados Unidos",
  "Chicago, Estados Unidos", "Boston, Estados Unidos", "Washington D. C., Estados Unidos",
  "Austin, Estados Unidos", "Houston, Estados Unidos", "Dallas, Estados Unidos",
  "Seattle, Estados Unidos", "Atlanta, Estados Unidos", "Denver, Estados Unidos",
  "Toronto, Canadá", "Montreal, Canadá", "Vancouver, Canadá", "Quebec, Canadá",

  // Europa
  "Madrid, España", "Barcelona, España", "Valencia, España", "Sevilla, España",
  "Bilbao, España", "Málaga, España", "Lisboa, Portugal", "Oporto, Portugal",
  "Londres, Reino Unido", "Manchester, Reino Unido", "Edimburgo, Reino Unido",
  "Dublín, Irlanda", "París, Francia", "Lyon, Francia", "Marsella, Francia",
  "Berlín, Alemania", "Múnich, Alemania", "Hamburgo, Alemania", "Ámsterdam, Países Bajos",
  "Bruselas, Bélgica", "Roma, Italia", "Milán, Italia", "Florencia, Italia",
  "Venecia, Italia", "Zúrich, Suiza", "Ginebra, Suiza", "Viena, Austria",
  "Praga, República Checa", "Budapest, Hungría", "Atenas, Grecia", "Copenhague, Dinamarca",
  "Estocolmo, Suecia", "Oslo, Noruega", "Helsinki, Finlandia", "Varsovia, Polonia",

  // Asia, Oceanía, África y Medio Oriente
  "Tokio, Japón", "Osaka, Japón", "Kioto, Japón", "Seúl, Corea del Sur",
  "Pekín, China", "Shanghái, China", "Hong Kong, China", "Taipéi, Taiwán",
  "Bangkok, Tailandia", "Singapur, Singapur", "Kuala Lumpur, Malasia", "Bali, Indonesia",
  "Nueva Delhi, India", "Bombay, India", "Dubái, Emiratos Árabes Unidos",
  "Abu Dabi, Emiratos Árabes Unidos", "Estambul, Turquía", "Tel Aviv, Israel",
  "Sídney, Australia", "Melbourne, Australia", "Brisbane, Australia", "Auckland, Nueva Zelanda",
  "Ciudad del Cabo, Sudáfrica", "Johannesburgo, Sudáfrica", "El Cairo, Egipto",
  "Marrakech, Marruecos", "Nairobi, Kenia",
] as const;
